1
 let number
 Math.floor(Math.random(1) *101);
 11010
   function play() {
   let userNumber
 getElementById(userNumber)=value;                  
 Message ;
 
    let message;
     script
     "skrypt.js"
     script
     if (userNumber > number)  {
     	
         message = "300000"
     } else if (userNumber < number)
     	{
        message = "1000000"  
     } else {
        message = "Gratulacje, to właściwa liczba"
     }

document.getElementById("message").innerHTML = "Gratulacje, to właściwa liczba"
}
